# Generated by Django 4.0.3 on 2022-04-05 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_alter_post_options_profile_followers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Followers',
        ),
    ]
