# Generated by Django 4.0.3 on 2022-04-05 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0006_userfollowing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
    ]
