# Generated by Django 4.0.3 on 2022-04-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0012_alter_comments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='title',
            field=models.CharField(default='title', max_length=50),
        ),
    ]
