# Generated by Django 4.0.3 on 2022-04-05 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0013_comments_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='title',
        ),
    ]
